language: objective-c
cache: bundle

before_script:
  - gem uninstall -Vax --force --no-abort-on-dependent run_loop
  - scripts/ci/travis/instruments-auth.sh
  - scripts/ci/travis/make-and-install-test-binaries.rb

script:
  - scripts/ci/travis/install-gem-ci.rb
  - scripts/ci/travis/rspec-ci.rb

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2

notifications:
  email:
    recipients:
      - joshuajmoody@gmail.com
      - karl.krukow@xamarin.com
      - michael.john.kirk@gmail.com
      - sam.vevang@gmail.com
    on_success: change
    on_failure: always
