# Force Xcode environment
language: objective-c

# Forces macOS 10.11
osx_image: xcode7.3

before_script:
  - scripts/ci/travis/instruments-auth.sh
  - scripts/ci/travis/make-and-install-test-binaries.rb

script:
  - scripts/ci/travis/install-gem-ci.rb
  - scripts/ci/travis/rspec-ci.rb

rvm:
  - 2.2.5
  - 2.3.1

notifications:
  email:
    recipients:
      - joshuajmoody@gmail.com
      - chris.fuentes@xamarin.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      secure: j15+d9xbUbGIyX4mmTmWP4EUg13LFiyeSGoVvpjsrPyoCR78V4jqbunLON55KczLQD5ql+xBwv34x57UZhca8g74ZBulF7A5xm7oxSyOgMOB1hgf5ruEU3n8dtWvHFvuLUyreu2QYrmGPznJnEOXE0feFuDBiyp1BpTvk4gwr+4=

